name: Continuous Training
on: 
  push:
    branches:
      - 'main'
      
jobs: 
  job-deploy:
    runs-on: ubuntu-latest
    environment: oh4ml-environment
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: az CLI login
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install ML extension for az command
      run: az extension add -n ml -y
    - name: Create ML Job
      run: az ml job create -f ./206_pipeline-diabetes.yml -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} -w ${{ secrets.AZURE_ML_WORKSPACE_NAME }}
